# Generated by Django 5.0.3 on 2024-04-01 16:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0002_studentextended_teacherextended'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundationalmodel',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Gentleman! This Email is not good.')], verbose_name='Email'),
        ),
    ]
