# Generated by Django 5.0.3 on 2024-04-01 17:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0003_alter_foundationalmodel_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextended',
            name='standard',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(limit_value=12, message='How you could study in this class?')]),
        ),
    ]
