# Generated by Django 5.0.3 on 2024-04-01 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0004_alter_studentextended_standard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextended',
            name='standard',
            field=models.IntegerField(),
        ),
    ]
