# Generated by Django 5.0.3 on 2024-04-01 19:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0006_alter_foundationalmodel_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='foundationalmodel',
            name='name',
            field=models.CharField(help_text='Please put your full name here', max_length=50, validators=[django.core.validators.MinLengthValidator(limit_value=5, message='Please enter name of good length.')], verbose_name='Name'),
        ),
    ]
