# Generated by Django 5.0.3 on 2024-04-01 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0008_alter_foundationalmodel_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundationalmodel',
            options={'verbose_name': 'Foundational Model'},
        ),
    ]
