# Generated by Django 5.0.3 on 2024-04-01 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0009_alter_foundationalmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='foundationalmodel',
            options={'verbose_name': 'Foundational Model', 'verbose_name_plural': 'Foundation Users'},
        ),
    ]
