# Generated by Django 5.0.3 on 2024-04-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0010_alter_foundationalmodel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Student', 'verbose_name_plural': 'Students'},
        ),
        migrations.AlterModelOptions(
            name='studentextended',
            options={'verbose_name': 'Student Extended', 'verbose_name_plural': 'Students Extended'},
        ),
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher', 'verbose_name_plural': 'Teachers'},
        ),
        migrations.AlterModelOptions(
            name='teacherextended',
            options={'verbose_name': 'Teacher Extended', 'verbose_name_plural': 'Teachers Extended'},
        ),
    ]
