# Generated by Django 5.0.3 on 2024-04-01 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0011_alter_student_options_alter_studentextended_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Baccha', 'verbose_name_plural': 'Students'},
        ),
    ]
