# Generated by Django 5.0.3 on 2024-04-01 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0012_alter_student_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Guruji', 'verbose_name_plural': 'Teachers'},
        ),
    ]
